[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NEXT_PUBLIC_SUPABASE_URL = "https://rvpvgkxdyatfhhfdyfrg.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_4AbWTTreyhQodW06gI1Z2A_TZHovb58"

[[plugins]]
  package = "@netlify/plugin-nextjs"
