import type { ScaleDefinition } from "@/lib/music-theory";

export type AllGuitarScaleDefinition = ScaleDefinition & {
  sourceId: number;
  steps: number[];
  scrapedFrom: "all-guitar-chords.com/scales";
};

export const ALL_GUITAR_SCALES = [
  {
    sourceId: 0,
    id: "major",
    scaleSlug: "major",
    name: "Major",
    category: "Common",
    formula: ["1", "2", "3", "4", "5", "6", "7"],
    steps: [0, 2, 4, 5, 7, 9, 11],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 1,
    id: "harmonic-minor",
    scaleSlug: "harmonic-minor",
    name: "Harmonic Minor",
    category: "Common",
    formula: ["1", "2", "b3", "4", "5", "b6", "7"],
    steps: [0, 2, 3, 5, 7, 8, 11],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 2,
    id: "melodic-minor",
    scaleSlug: "melodic-minor",
    name: "Melodic Minor",
    category: "Common",
    formula: ["1", "2", "b3", "4", "5", "6", "7"],
    steps: [0, 2, 3, 5, 7, 9, 11],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 3,
    id: "natural-minor",
    scaleSlug: "natural-minor",
    name: "Natural Minor",
    category: "Common",
    formula: ["1", "2", "b3", "4", "5", "b6", "b7"],
    steps: [0, 2, 3, 5, 7, 8, 10],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 4,
    id: "chromatic",
    scaleSlug: "chromatic",
    name: "Chromatic",
    category: "Rare",
    formula: ["1", "b2", "2", "b3", "3", "4", "b5", "5", "#5", "6", "b7", "7"],
    steps: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 5,
    id: "whole-tone",
    scaleSlug: "whole-tone",
    name: "Whole Tone",
    category: "Rare",
    formula: ["1", "2", "3", "#4", "#5", "b7"],
    steps: [0, 2, 4, 6, 8, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 6,
    id: "pentatonic-major",
    scaleSlug: "pentatonic-major",
    name: "Pentatonic Major",
    category: "Common",
    formula: ["1", "2", "3", "5", "6"],
    steps: [0, 2, 4, 7, 9],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 7,
    id: "pentatonic-minor",
    scaleSlug: "pentatonic-minor",
    name: "Pentatonic Minor",
    category: "Common",
    formula: ["1", "b3", "4", "5", "b7"],
    steps: [0, 3, 5, 7, 10],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 8,
    id: "pentatonic-blues",
    scaleSlug: "pentatonic-blues",
    name: "Pentatonic Blues",
    category: "Common",
    formula: ["1", "b3", "4", "b5", "5", "b7"],
    steps: [0, 3, 5, 6, 7, 10],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 9,
    id: "pentatonic-neutral",
    scaleSlug: "pentatonic-neutral",
    name: "Pentatonic Neutral",
    category: "Common",
    formula: ["1", "2", "4", "5", "b7"],
    steps: [0, 2, 5, 7, 10],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 10,
    id: "octatonic-h-w",
    scaleSlug: "octatonic-h-w",
    name: "Octatonic (H-W)",
    category: "Rare",
    formula: ["1", "b2", "b3", "3", "b5", "5", "6", "b7"],
    steps: [0, 1, 3, 4, 6, 7, 9, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 11,
    id: "octatonic-w-h",
    scaleSlug: "octatonic-w-h",
    name: "Octatonic (W-H)",
    category: "Rare",
    formula: ["1", "2", "b3", "4", "b5", "b6", "6", "7"],
    steps: [0, 2, 3, 5, 6, 8, 9, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 12,
    id: "ionian",
    scaleSlug: "ionian",
    name: "Ionian",
    category: "Common",
    formula: ["1", "2", "3", "4", "5", "6", "7"],
    steps: [0, 2, 4, 5, 7, 9, 11],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 13,
    id: "dorian",
    scaleSlug: "dorian",
    name: "Dorian",
    category: "Common",
    formula: ["1", "2", "b3", "4", "5", "6", "b7"],
    steps: [0, 2, 3, 5, 7, 9, 10],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 14,
    id: "phrygian",
    scaleSlug: "phrygian",
    name: "Phrygian",
    category: "Common",
    formula: ["1", "b2", "b3", "4", "5", "b6", "b7"],
    steps: [0, 1, 3, 5, 7, 8, 10],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 15,
    id: "lydian",
    scaleSlug: "lydian",
    name: "Lydian",
    category: "Common",
    formula: ["1", "2", "3", "#4", "5", "6", "7"],
    steps: [0, 2, 4, 6, 7, 9, 11],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 16,
    id: "mixolydian",
    scaleSlug: "mixolydian",
    name: "Mixolydian",
    category: "Common",
    formula: ["1", "2", "3", "4", "5", "6", "b7"],
    steps: [0, 2, 4, 5, 7, 9, 10],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 17,
    id: "aeolian",
    scaleSlug: "aeolian",
    name: "Aeolian",
    category: "Common",
    formula: ["1", "2", "b3", "4", "5", "b6", "b7"],
    steps: [0, 2, 3, 5, 7, 8, 10],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 18,
    id: "locrian",
    scaleSlug: "locrian",
    name: "Locrian",
    category: "Common",
    formula: ["1", "b2", "b3", "4", "b5", "b6", "b7"],
    steps: [0, 1, 3, 5, 6, 8, 10],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 19,
    id: "algerian",
    scaleSlug: "algerian",
    name: "Algerian",
    category: "Exotic",
    formula: ["1", "2", "b3", "4", "#4", "5", "b6", "7"],
    steps: [0, 2, 3, 5, 6, 7, 8, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 20,
    id: "arabian-a",
    scaleSlug: "arabian-a",
    name: "Arabian (a)",
    category: "Exotic",
    formula: ["1", "2", "b3", "4", "#4", "#5", "6", "7"],
    steps: [0, 2, 3, 5, 6, 8, 9, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 21,
    id: "arabian-b",
    scaleSlug: "arabian-b",
    name: "Arabian (b)",
    category: "Exotic",
    formula: ["1", "2", "3", "4", "#4", "#5", "b7"],
    steps: [0, 2, 4, 5, 6, 8, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 22,
    id: "augmented",
    scaleSlug: "augmented",
    name: "Augmented",
    category: "Rare",
    formula: ["1", "#2", "3", "#4", "#5", "7"],
    steps: [0, 3, 4, 6, 8, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 23,
    id: "auxiliary-diminished",
    scaleSlug: "auxiliary-diminished",
    name: "Auxiliary Diminished",
    category: "Rare",
    formula: ["1", "2", "b3", "4", "#4", "#5", "6", "7"],
    steps: [0, 2, 3, 5, 6, 8, 9, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 24,
    id: "auxiliary-augmented",
    scaleSlug: "auxiliary-augmented",
    name: "Auxiliary Augmented",
    category: "Rare",
    formula: ["1", "2", "3", "#4", "#5", "#6"],
    steps: [0, 2, 4, 6, 8, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 25,
    id: "auxiliary-diminished-blues",
    scaleSlug: "auxiliary-diminished-blues",
    name: "Auxiliary Diminished Blues",
    category: "Rare",
    formula: ["1", "b2", "b3", "3", "b5", "5", "6", "b7"],
    steps: [0, 1, 3, 4, 6, 7, 9, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 26,
    id: "balinese",
    scaleSlug: "balinese",
    name: "Balinese",
    category: "Exotic",
    formula: ["1", "b2", "b3", "5", "b6"],
    steps: [0, 1, 3, 7, 8],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 27,
    id: "blues",
    scaleSlug: "blues",
    name: "Blues",
    category: "Rare",
    formula: ["1", "b3", "4", "#4", "5", "b7"],
    steps: [0, 3, 5, 6, 7, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 28,
    id: "byzantine",
    scaleSlug: "byzantine",
    name: "Byzantine",
    category: "Exotic",
    formula: ["1", "b2", "3", "4", "5", "b6", "7"],
    steps: [0, 1, 4, 5, 7, 8, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 29,
    id: "chinese",
    scaleSlug: "chinese",
    name: "Chinese",
    category: "Exotic",
    formula: ["1", "3", "#4", "5", "7"],
    steps: [0, 4, 6, 7, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 30,
    id: "chinese-mongolian",
    scaleSlug: "chinese-mongolian",
    name: "Chinese Mongolian",
    category: "Exotic",
    formula: ["1", "2", "3", "5", "6"],
    steps: [0, 2, 4, 7, 9],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 31,
    id: "diatonic",
    scaleSlug: "diatonic",
    name: "Diatonic",
    category: "Common",
    formula: ["1", "2", "3", "5", "6"],
    steps: [0, 2, 4, 7, 9],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 32,
    id: "diminished",
    scaleSlug: "diminished",
    name: "Diminished",
    category: "Common",
    formula: ["1", "2", "b3", "4", "b5", "b6", "6", "7"],
    steps: [0, 2, 3, 5, 6, 8, 9, 11],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 33,
    id: "diminished-half",
    scaleSlug: "diminished-half",
    name: "Diminished, Half",
    category: "Common",
    formula: ["1", "b2", "b3", "3", "b5", "5", "6", "b7"],
    steps: [0, 1, 3, 4, 6, 7, 9, 10],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 34,
    id: "diminished-whole",
    scaleSlug: "diminished-whole",
    name: "Diminished, Whole",
    category: "Common",
    formula: ["1", "2", "b3", "4", "b5", "b6", "6", "7"],
    steps: [0, 2, 3, 5, 6, 8, 9, 11],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 35,
    id: "diminished-whole-tone",
    scaleSlug: "diminished-whole-tone",
    name: "Diminished Whole Tone",
    category: "Common",
    formula: ["1", "b2", "b3", "3", "b5", "b6", "b7"],
    steps: [0, 1, 3, 4, 6, 8, 10],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 36,
    id: "dominant-7th",
    scaleSlug: "dominant-7th",
    name: "Dominant 7th",
    category: "Common",
    formula: ["1", "2", "3", "4", "5", "6", "b7"],
    steps: [0, 2, 4, 5, 7, 9, 10],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 37,
    id: "double-harmonic",
    scaleSlug: "double-harmonic",
    name: "Double Harmonic",
    category: "Rare",
    formula: ["1", "b2", "3", "4", "5", "b6", "7"],
    steps: [0, 1, 4, 5, 7, 8, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 38,
    id: "egyptian",
    scaleSlug: "egyptian",
    name: "Egyptian",
    category: "Exotic",
    formula: ["1", "2", "4", "5", "b7"],
    steps: [0, 2, 5, 7, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 39,
    id: "eight-tone-spanish",
    scaleSlug: "eight-tone-spanish",
    name: "Eight Tone Spanish",
    category: "Exotic",
    formula: ["1", "b2", "#2", "3", "4", "b5", "b6", "b7"],
    steps: [0, 1, 3, 4, 5, 6, 8, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 40,
    id: "enigmatic",
    scaleSlug: "enigmatic",
    name: "Enigmatic",
    category: "Rare",
    formula: ["1", "b2", "3", "#4", "#5", "#6", "7"],
    steps: [0, 1, 4, 6, 8, 10, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 41,
    id: "ethiopian-a-raray",
    scaleSlug: "ethiopian-a-raray",
    name: "Ethiopian (A raray)",
    category: "Exotic",
    formula: ["1", "2", "3", "4", "5", "6", "7"],
    steps: [0, 2, 4, 5, 7, 9, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 42,
    id: "ethiopian-geez-and-ezel",
    scaleSlug: "ethiopian-geez-and-ezel",
    name: "Ethiopian (Geez & Ezel)",
    category: "Exotic",
    formula: ["1", "2", "b3", "4", "5", "b6", "b7"],
    steps: [0, 2, 3, 5, 7, 8, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 43,
    id: "half-diminished-locrian",
    scaleSlug: "half-diminished-locrian",
    name: "Half Diminished (Locrian)",
    category: "Rare",
    formula: ["1", "b2", "b3", "4", "b5", "b6", "b7"],
    steps: [0, 1, 3, 5, 6, 8, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 44,
    id: "half-diminished-sharp2-locrian-sharp2",
    scaleSlug: "half-diminished-sharp2-locrian-sharp2",
    name: "Half Diminished #2 (Locrian #2)",
    category: "Rare",
    formula: ["1", "2", "b3", "4", "b5", "b6", "b7"],
    steps: [0, 2, 3, 5, 6, 8, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 45,
    id: "hawaiian",
    scaleSlug: "hawaiian",
    name: "Hawaiian",
    category: "Exotic",
    formula: ["1", "2", "b3", "4", "5", "6", "7"],
    steps: [0, 2, 3, 5, 7, 9, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 46,
    id: "hindu",
    scaleSlug: "hindu",
    name: "Hindu",
    category: "Exotic",
    formula: ["1", "2", "3", "4", "5", "b6", "b7"],
    steps: [0, 2, 4, 5, 7, 8, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 47,
    id: "hindustan",
    scaleSlug: "hindustan",
    name: "Hindustan",
    category: "Exotic",
    formula: ["1", "2", "3", "4", "5", "b6", "b7"],
    steps: [0, 2, 4, 5, 7, 8, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 48,
    id: "hirajoshi",
    scaleSlug: "hirajoshi",
    name: "Hirajoshi",
    category: "Exotic",
    formula: ["1", "2", "b3", "5", "b6"],
    steps: [0, 2, 3, 7, 8],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 49,
    id: "hungarian-major",
    scaleSlug: "hungarian-major",
    name: "Hungarian Major",
    category: "Exotic",
    formula: ["1", "#2", "3", "#4", "5", "6", "b7"],
    steps: [0, 3, 4, 6, 7, 9, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 50,
    id: "hungarian-gypsy",
    scaleSlug: "hungarian-gypsy",
    name: "Hungarian Gypsy",
    category: "Exotic",
    formula: ["1", "2", "b3", "#4", "5", "b6", "7"],
    steps: [0, 2, 3, 6, 7, 8, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 51,
    id: "hungarian-gypsy-persian",
    scaleSlug: "hungarian-gypsy-persian",
    name: "Hungarian Gypsy Persian",
    category: "Exotic",
    formula: ["1", "b2", "3", "4", "5", "b6", "7"],
    steps: [0, 1, 4, 5, 7, 8, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 52,
    id: "hungarian-minor",
    scaleSlug: "hungarian-minor",
    name: "Hungarian Minor",
    category: "Exotic",
    formula: ["1", "2", "b3", "#4", "5", "b6", "7"],
    steps: [0, 2, 3, 6, 7, 8, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 53,
    id: "japanese-a",
    scaleSlug: "japanese-a",
    name: "Japanese (A)",
    category: "Exotic",
    formula: ["1", "b2", "4", "5", "b6"],
    steps: [0, 1, 5, 7, 8],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 54,
    id: "japanese-b",
    scaleSlug: "japanese-b",
    name: "Japanese (B)",
    category: "Exotic",
    formula: ["1", "2", "4", "5", "b6"],
    steps: [0, 2, 5, 7, 8],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 55,
    id: "japanese-ichikosucho",
    scaleSlug: "japanese-ichikosucho",
    name: "Japanese (Ichikosucho)",
    category: "Exotic",
    formula: ["1", "2", "3", "4", "#4", "5", "6", "7"],
    steps: [0, 2, 4, 5, 6, 7, 9, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 56,
    id: "japanese-taishikicho",
    scaleSlug: "japanese-taishikicho",
    name: "Japanese (Taishikicho)",
    category: "Exotic",
    formula: ["1", "2", "3", "4", "#4", "5", "6", "#6", "7"],
    steps: [0, 2, 4, 5, 6, 7, 9, 10, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 57,
    id: "javaneese",
    scaleSlug: "javaneese",
    name: "Javaneese",
    category: "Exotic",
    formula: ["1", "b2", "b3", "4", "5", "6", "b7"],
    steps: [0, 1, 3, 5, 7, 9, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 58,
    id: "jewish-adonai-malakh",
    scaleSlug: "jewish-adonai-malakh",
    name: "Jewish (Adonai Malakh)",
    category: "Exotic",
    formula: ["1", "b2", "2", "b3", "4", "5", "6", "b7"],
    steps: [0, 1, 2, 3, 5, 7, 9, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 59,
    id: "jewish-ahaba-rabba",
    scaleSlug: "jewish-ahaba-rabba",
    name: "Jewish (Ahaba Rabba)",
    category: "Exotic",
    formula: ["1", "b2", "3", "4", "5", "b6", "b7"],
    steps: [0, 1, 4, 5, 7, 8, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 60,
    id: "jewish-magen-abot",
    scaleSlug: "jewish-magen-abot",
    name: "Jewish (Magen Abot)",
    category: "Exotic",
    formula: ["1", "b2", "#2", "3", "#4", "#5", "#6", "7"],
    steps: [0, 1, 3, 4, 6, 8, 10, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 61,
    id: "kumoi",
    scaleSlug: "kumoi",
    name: "Kumoi",
    category: "Exotic",
    formula: ["1", "2", "b3", "5", "6"],
    steps: [0, 2, 3, 7, 9],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 62,
    id: "leading-whole-tone",
    scaleSlug: "leading-whole-tone",
    name: "Leading Whole Tone",
    category: "Rare",
    formula: ["1", "2", "3", "#4", "#5", "#6", "7"],
    steps: [0, 2, 4, 6, 8, 10, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 63,
    id: "lydian-augmented",
    scaleSlug: "lydian-augmented",
    name: "Lydian Augmented",
    category: "Common",
    formula: ["1", "2", "3", "#4", "#5", "6", "7"],
    steps: [0, 2, 4, 6, 8, 9, 11],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 64,
    id: "lydian-minor",
    scaleSlug: "lydian-minor",
    name: "Lydian Minor",
    category: "Common",
    formula: ["1", "2", "3", "#4", "5", "b6", "b7"],
    steps: [0, 2, 4, 6, 7, 8, 10],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 65,
    id: "lydian-diminished",
    scaleSlug: "lydian-diminished",
    name: "Lydian Diminished",
    category: "Common",
    formula: ["1", "2", "b3", "#4", "5", "6", "7"],
    steps: [0, 2, 3, 6, 7, 9, 11],
    character: "All-Guitar-Chords Common gamı.",
    genres: ["Common"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 66,
    id: "major-locrian",
    scaleSlug: "major-locrian",
    name: "Major Locrian",
    category: "Rare",
    formula: ["1", "2", "3", "4", "b5", "b6", "b7"],
    steps: [0, 2, 4, 5, 6, 8, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 67,
    id: "mohammedan",
    scaleSlug: "mohammedan",
    name: "Mohammedan",
    category: "Exotic",
    formula: ["1", "2", "b3", "4", "5", "b6", "7"],
    steps: [0, 2, 3, 5, 7, 8, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 68,
    id: "neopolitan",
    scaleSlug: "neopolitan",
    name: "Neopolitan",
    category: "Exotic",
    formula: ["1", "b2", "b3", "4", "5", "b6", "7"],
    steps: [0, 1, 3, 5, 7, 8, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 69,
    id: "neoploitan-major",
    scaleSlug: "neoploitan-major",
    name: "Neoploitan Major",
    category: "Exotic",
    formula: ["1", "b2", "b3", "4", "5", "6", "7"],
    steps: [0, 1, 3, 5, 7, 9, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 70,
    id: "neopolitan-minor",
    scaleSlug: "neopolitan-minor",
    name: "Neopolitan Minor",
    category: "Exotic",
    formula: ["1", "b2", "b3", "4", "5", "b6", "b7"],
    steps: [0, 1, 3, 5, 7, 8, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 71,
    id: "nine-tone-scale",
    scaleSlug: "nine-tone-scale",
    name: "Nine Tone Scale",
    category: "Rare",
    formula: ["1", "2", "#2", "3", "#4", "5", "#5", "6", "7"],
    steps: [0, 2, 3, 4, 6, 7, 8, 9, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 72,
    id: "oriental-a",
    scaleSlug: "oriental-a",
    name: "Oriental (a)",
    category: "Exotic",
    formula: ["1", "b2", "3", "4", "b5", "b6", "b7"],
    steps: [0, 1, 4, 5, 6, 8, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 73,
    id: "oriental-b",
    scaleSlug: "oriental-b",
    name: "Oriental (b)",
    category: "Exotic",
    formula: ["1", "b2", "3", "4", "b5", "6", "b7"],
    steps: [0, 1, 4, 5, 6, 9, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 74,
    id: "overtone",
    scaleSlug: "overtone",
    name: "Overtone",
    category: "Rare",
    formula: ["1", "2", "3", "#4", "5", "6", "b7"],
    steps: [0, 2, 4, 6, 7, 9, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 75,
    id: "overtone-dominant",
    scaleSlug: "overtone-dominant",
    name: "Overtone Dominant",
    category: "Rare",
    formula: ["1", "2", "3", "#4", "5", "6", "b7"],
    steps: [0, 2, 4, 6, 7, 9, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 76,
    id: "pelog",
    scaleSlug: "pelog",
    name: "Pelog",
    category: "Exotic",
    formula: ["1", "b2", "b3", "5", "b6"],
    steps: [0, 1, 3, 7, 8],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 77,
    id: "persian",
    scaleSlug: "persian",
    name: "Persian",
    category: "Exotic",
    formula: ["1", "b2", "3", "4", "b5", "b6", "7"],
    steps: [0, 1, 4, 5, 6, 8, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 78,
    id: "prometheus",
    scaleSlug: "prometheus",
    name: "Prometheus",
    category: "Exotic",
    formula: ["1", "2", "3", "b5", "6", "b7"],
    steps: [0, 2, 4, 6, 9, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 79,
    id: "prometheus-neopolitan",
    scaleSlug: "prometheus-neopolitan",
    name: "Prometheus Neopolitan",
    category: "Exotic",
    formula: ["1", "b2", "3", "b5", "6", "b7"],
    steps: [0, 1, 4, 6, 9, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 81,
    id: "roumanian-minor",
    scaleSlug: "roumanian-minor",
    name: "Roumanian Minor",
    category: "Exotic",
    formula: ["1", "2", "b3", "#4", "5", "6", "b7"],
    steps: [0, 2, 3, 6, 7, 9, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 82,
    id: "six-tone-symmetrical",
    scaleSlug: "six-tone-symmetrical",
    name: "Six Tone Symmetrical",
    category: "Rare",
    formula: ["1", "b2", "3", "4", "#5", "6"],
    steps: [0, 1, 4, 5, 8, 9],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 83,
    id: "spanish-gypsy",
    scaleSlug: "spanish-gypsy",
    name: "Spanish Gypsy",
    category: "Exotic",
    formula: ["1", "b2", "3", "4", "5", "b6", "b7"],
    steps: [0, 1, 4, 5, 7, 8, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 84,
    id: "super-locrian",
    scaleSlug: "super-locrian",
    name: "Super Locrian",
    category: "Exotic",
    formula: ["1", "b2", "#2", "3", "#4", "#5", "b7"],
    steps: [0, 1, 3, 4, 6, 8, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 85,
    id: "altered",
    scaleSlug: "altered",
    name: "Altered",
    category: "Rare",
    formula: ["1", "b2", "b3", "b4", "b5", "b6", "b7"],
    steps: [0, 1, 3, 4, 6, 7, 8],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 86,
    id: "bebop-major",
    scaleSlug: "bebop-major",
    name: "Bebop Major",
    category: "Rare",
    formula: ["1", "2", "3", "4", "5", "#5", "6", "7"],
    steps: [0, 2, 4, 5, 7, 8, 9, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 87,
    id: "bebop-minor",
    scaleSlug: "bebop-minor",
    name: "Bebop Minor",
    category: "Rare",
    formula: ["1", "2", "b3", "3", "4", "5", "6", "b7"],
    steps: [0, 2, 3, 4, 5, 7, 9, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 88,
    id: "bebop-dominant",
    scaleSlug: "bebop-dominant",
    name: "Bebop Dominant",
    category: "Rare",
    formula: ["1", "2", "3", "4", "5", "6", "b7", "7"],
    steps: [0, 2, 4, 5, 7, 9, 10, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 89,
    id: "bebop-half-diminished",
    scaleSlug: "bebop-half-diminished",
    name: "Bebop Half Diminished",
    category: "Rare",
    formula: ["1", "b2", "b3", "4", "b5", "5", "b6", "7"],
    steps: [0, 1, 3, 5, 6, 7, 8, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 90,
    id: "blues-variation-1",
    scaleSlug: "blues-variation-1",
    name: "Blues Variation 1",
    category: "Rare",
    formula: ["1", "b3", "4", "b5", "5", "b7", "7"],
    steps: [0, 3, 5, 6, 7, 10, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 91,
    id: "blues-variation-2",
    scaleSlug: "blues-variation-2",
    name: "Blues Variation 2",
    category: "Rare",
    formula: ["1", "b3", "3", "4", "b5", "5", "b7", "7"],
    steps: [0, 3, 4, 5, 6, 7, 10, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 92,
    id: "blues-variation-3",
    scaleSlug: "blues-variation-3",
    name: "Blues Variation 3",
    category: "Rare",
    formula: ["1", "b3", "3", "4", "b5", "5", "6", "b7", "7"],
    steps: [0, 3, 4, 5, 6, 7, 9, 10, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 93,
    id: "major-blues-scale",
    scaleSlug: "major-blues-scale",
    name: "Major Blues Scale",
    category: "Rare",
    formula: ["1", "2", "b3", "3", "5", "6"],
    steps: [0, 2, 3, 4, 7, 9],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 94,
    id: "dominant-pentatonic",
    scaleSlug: "dominant-pentatonic",
    name: "Dominant Pentatonic",
    category: "Rare",
    formula: ["1", "2", "3", "5", "b7"],
    steps: [0, 2, 4, 7, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 95,
    id: "chinese-2",
    scaleSlug: "chinese-2",
    name: "Chinese 2",
    category: "Exotic",
    formula: ["1", "2", "4", "5", "6"],
    steps: [0, 2, 5, 7, 9],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 96,
    id: "hirajoshi-2",
    scaleSlug: "hirajoshi-2",
    name: "Hirajoshi 2",
    category: "Exotic",
    formula: ["1", "3", "4", "6", "7"],
    steps: [0, 4, 5, 9, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 97,
    id: "iwato",
    scaleSlug: "iwato",
    name: "Iwato",
    category: "Exotic",
    formula: ["1", "b2", "4", "b5", "b7"],
    steps: [0, 1, 5, 6, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 98,
    id: "japanese-in-sen",
    scaleSlug: "japanese-in-sen",
    name: "Japanese (in sen)",
    category: "Exotic",
    formula: ["1", "b2", "4", "5", "b7"],
    steps: [0, 1, 5, 7, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 99,
    id: "kumoi-2",
    scaleSlug: "kumoi-2",
    name: "Kumoi 2",
    category: "Exotic",
    formula: ["1", "b2", "4", "5", "b6"],
    steps: [0, 1, 5, 7, 8],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 100,
    id: "pelog-2",
    scaleSlug: "pelog-2",
    name: "Pelog 2",
    category: "Exotic",
    formula: ["1", "b2", "b3", "5", "b7"],
    steps: [0, 1, 3, 7, 10],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 101,
    id: "locrian-6",
    scaleSlug: "locrian-6",
    name: "Locrian 6",
    category: "Rare",
    formula: ["1", "b2", "b3", "4", "b5", "6", "b7"],
    steps: [0, 1, 3, 5, 6, 9, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 102,
    id: "ionian-sharp5",
    scaleSlug: "ionian-sharp5",
    name: "Ionian #5",
    category: "Rare",
    formula: ["1", "2", "3", "4", "#5", "6", "7"],
    steps: [0, 2, 4, 5, 8, 9, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 103,
    id: "dorian-sharp4",
    scaleSlug: "dorian-sharp4",
    name: "Dorian #4",
    category: "Rare",
    formula: ["1", "2", "b3", "#4", "5", "6", "b7"],
    steps: [0, 2, 3, 6, 7, 9, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 104,
    id: "phrygian-major",
    scaleSlug: "phrygian-major",
    name: "Phrygian Major",
    category: "Rare",
    formula: ["1", "b2", "3", "4", "5", "b6", "b7"],
    steps: [0, 1, 4, 5, 7, 8, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 105,
    id: "lydian-sharp2",
    scaleSlug: "lydian-sharp2",
    name: "Lydian #2",
    category: "Rare",
    formula: ["1", "#2", "3", "#4", "5", "6", "7"],
    steps: [0, 3, 4, 6, 7, 9, 11],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 106,
    id: "ultralocrian",
    scaleSlug: "ultralocrian",
    name: "Ultralocrian",
    category: "Rare",
    formula: ["1", "b2", "b3", "3", "b5", "b6", "6"],
    steps: [0, 1, 3, 4, 6, 8, 9],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 107,
    id: "moorish-phrygian",
    scaleSlug: "moorish-phrygian",
    name: "Moorish Phrygian",
    category: "Exotic",
    formula: ["1", "b2", "b3", "3", "4", "5", "#5", "b7", "7"],
    steps: [0, 1, 3, 4, 5, 7, 8, 10, 11],
    character: "All-Guitar-Chords Exotic gamı.",
    genres: ["Exotic"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
  {
    sourceId: 108,
    id: "mixo-blues",
    scaleSlug: "mixo-blues",
    name: "Mixo-Blues",
    category: "Rare",
    formula: ["1", "b3", "3", "4", "b5", "5", "b7"],
    steps: [0, 3, 4, 5, 6, 7, 10],
    character: "All-Guitar-Chords Rare gamı.",
    genres: ["Rare"],
    scrapedFrom: "all-guitar-chords.com/scales",
  },
] satisfies AllGuitarScaleDefinition[];
