create table if not exists public.setlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.setlist_songs (
  id bigint generated by default as identity primary key,
  setlist_id bigint not null references public.setlists(id) on delete cascade,
  song_id bigint not null references public.songs(id) on delete cascade,
  position integer not null default 1,
  created_at timestamptz not null default now(),
  unique (setlist_id, song_id)
);

create index if not exists setlists_user_id_created_at_idx on public.setlists(user_id, created_at desc);
create index if not exists setlist_songs_setlist_id_position_idx on public.setlist_songs(setlist_id, position);

alter table public.setlists enable row level security;
alter table public.setlist_songs enable row level security;

drop policy if exists "Users can manage own setlists" on public.setlists;
create policy "Users can manage own setlists"
  on public.setlists
  for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can manage own setlist songs" on public.setlist_songs;
create policy "Users can manage own setlist songs"
  on public.setlist_songs
  for all
  using (
    exists (
      select 1 from public.setlists
      where setlists.id = setlist_songs.setlist_id
        and setlists.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.setlists
      where setlists.id = setlist_songs.setlist_id
        and setlists.user_id = auth.uid()
    )
  );
