create table if not exists public.learning_tabs (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  artist text not null,
  artist_slug text not null,
  status text not null default 'published' check (status in ('draft', 'private', 'published')),
  source_type text not null default 'user' check (source_type in ('user', 'import', 'ai', 'licensed', 'demo')),
  tuning text,
  capo text,
  bpm integer,
  key text,
  instruments text[] not null default '{}',
  tab_text text not null default '',
  contributor_id uuid references auth.users(id) on delete set null,
  contributor_name text,
  revision_number integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.learning_tab_tracks (
  id bigint generated by default as identity primary key,
  tab_id bigint not null references public.learning_tabs(id) on delete cascade,
  name text not null,
  instrument text not null,
  tuning text,
  volume integer not null default 80,
  muted boolean not null default false,
  solo boolean not null default false,
  tab_text text not null default '',
  midi_data jsonb,
  position integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.learning_tab_revisions (
  id bigint generated by default as identity primary key,
  tab_id bigint not null references public.learning_tabs(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  revision_number integer not null,
  change_note text,
  tab_snapshot jsonb not null,
  created_at timestamptz not null default now(),
  unique (tab_id, revision_number)
);

create table if not exists public.learning_playlists (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.learning_playlist_items (
  id bigint generated by default as identity primary key,
  playlist_id bigint not null references public.learning_playlists(id) on delete cascade,
  tab_id bigint not null references public.learning_tabs(id) on delete cascade,
  position integer not null default 1,
  created_at timestamptz not null default now(),
  unique (playlist_id, tab_id)
);

create table if not exists public.learning_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tab_id bigint not null references public.learning_tabs(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, tab_id)
);

create table if not exists public.learning_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tab_id bigint not null references public.learning_tabs(id) on delete cascade,
  opened_at timestamptz not null default now(),
  unique (user_id, tab_id)
);

create index if not exists learning_tabs_artist_slug_idx on public.learning_tabs(artist_slug);
create index if not exists learning_tabs_status_created_at_idx on public.learning_tabs(status, created_at desc);
create index if not exists learning_tab_tracks_tab_id_position_idx on public.learning_tab_tracks(tab_id, position);
create index if not exists learning_playlists_user_id_created_at_idx on public.learning_playlists(user_id, created_at desc);
create index if not exists learning_history_user_id_opened_at_idx on public.learning_history(user_id, opened_at desc);

alter table public.learning_tabs enable row level security;
alter table public.learning_tab_tracks enable row level security;
alter table public.learning_tab_revisions enable row level security;
alter table public.learning_playlists enable row level security;
alter table public.learning_playlist_items enable row level security;
alter table public.learning_favorites enable row level security;
alter table public.learning_history enable row level security;

drop policy if exists "Users can read published learning tabs" on public.learning_tabs;
create policy "Users can read published learning tabs"
  on public.learning_tabs for select
  using (status = 'published' or contributor_id = auth.uid());

drop policy if exists "Users can create own learning tabs" on public.learning_tabs;
create policy "Users can create own learning tabs"
  on public.learning_tabs for insert
  with check (contributor_id = auth.uid());

drop policy if exists "Users can update own learning tabs" on public.learning_tabs;
create policy "Users can update own learning tabs"
  on public.learning_tabs for update
  using (contributor_id = auth.uid())
  with check (contributor_id = auth.uid());

drop policy if exists "Users can read tracks for readable learning tabs" on public.learning_tab_tracks;
create policy "Users can read tracks for readable learning tabs"
  on public.learning_tab_tracks for select
  using (exists (select 1 from public.learning_tabs where learning_tabs.id = learning_tab_tracks.tab_id and (learning_tabs.status = 'published' or learning_tabs.contributor_id = auth.uid())));

drop policy if exists "Users can manage tracks for own learning tabs" on public.learning_tab_tracks;
create policy "Users can manage tracks for own learning tabs"
  on public.learning_tab_tracks for all
  using (exists (select 1 from public.learning_tabs where learning_tabs.id = learning_tab_tracks.tab_id and learning_tabs.contributor_id = auth.uid()))
  with check (exists (select 1 from public.learning_tabs where learning_tabs.id = learning_tab_tracks.tab_id and learning_tabs.contributor_id = auth.uid()));

drop policy if exists "Users can read revisions for readable learning tabs" on public.learning_tab_revisions;
create policy "Users can read revisions for readable learning tabs"
  on public.learning_tab_revisions for select
  using (exists (select 1 from public.learning_tabs where learning_tabs.id = learning_tab_revisions.tab_id and (learning_tabs.status = 'published' or learning_tabs.contributor_id = auth.uid())));

drop policy if exists "Users can create revisions for own learning tabs" on public.learning_tab_revisions;
create policy "Users can create revisions for own learning tabs"
  on public.learning_tab_revisions for insert
  with check (exists (select 1 from public.learning_tabs where learning_tabs.id = learning_tab_revisions.tab_id and learning_tabs.contributor_id = auth.uid()));

drop policy if exists "Users can manage own learning playlists" on public.learning_playlists;
create policy "Users can manage own learning playlists"
  on public.learning_playlists for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can manage own learning playlist items" on public.learning_playlist_items;
create policy "Users can manage own learning playlist items"
  on public.learning_playlist_items for all
  using (exists (select 1 from public.learning_playlists where learning_playlists.id = learning_playlist_items.playlist_id and learning_playlists.user_id = auth.uid()))
  with check (exists (select 1 from public.learning_playlists where learning_playlists.id = learning_playlist_items.playlist_id and learning_playlists.user_id = auth.uid()));

drop policy if exists "Users can manage own learning favorites" on public.learning_favorites;
create policy "Users can manage own learning favorites"
  on public.learning_favorites for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can manage own learning history" on public.learning_history;
create policy "Users can manage own learning history"
  on public.learning_history for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

insert into public.learning_tabs (slug, title, artist, artist_slug, status, source_type, tuning, bpm, instruments, tab_text, contributor_name, revision_number)
values
  ('guitarhub-demo-riff', 'GuitarHub Demo Riff', 'GuitarHub Studio', 'guitarhub-studio', 'published', 'demo', 'E A D G B E', 90, array['Gitar','Bas','Davul'], 'e|----------------|----------------|
B|-----0-----1----|-----3-----1----|
G|---0-----0------|---0-----0------|
D|----------------|----------------|
A|-3-----3--------|-2-----2--------|
E|----------------|----------------|', 'GuitarHub', 1),
  ('akustik-arpej-calismasi', 'Akustik Arpej Çalışması', 'GuitarHub Studio', 'guitarhub-studio', 'published', 'demo', 'E A D G B E', 76, array['Gitar','Vokal'], 'e|-----0-------0--|-----0-------0--|
B|---1---1---1----|---3---3---3----|
G|-0-------0------|-0-------0------|
D|----------------|----------------|
A|3---------------|2---------------|
E|----------------|----------------|', 'Yoda', 2),
  ('bas-groove-90-bpm', 'Bas Groove 90 BPM', 'GuitarHub Studio', 'guitarhub-studio', 'published', 'demo', 'E A D G', 90, array['Bas','Davul','Klavye'], 'G|----------------|----------------|
D|-----2-----2----|-----4-----2----|
A|---2-----2------|---2-----2------|
E|-0-----0--------|-3-----3--------|', 'Community', 1)
on conflict (slug) do nothing;
